baseURL = "http://skyclerk.com/"
languageCode = "en-us"
title = "Skyclerk"
publishDir = "docs"
disableHugoGeneratorInject = true
disableKinds = ["taxonomyTerm"]
summaryLength = 20

[permalinks]
	categories = "/blog/:slug/"
