baseURL = "https://skyclerk.com/"
languageCode = "en-us"
title = "Skyclerk"
publishDir = "docs"
disableHugoGeneratorInject = true
disableKinds = ["taxonomyTerm"]
summaryLength = 20

[taxonomies]
  category = "categories"
  supportCategory = "supportCategories"

[permalinks]
	categories = "/blog/:slug/"

[outputs]
  home = ["HTML", "RSS", "JSON"]
