baseURL = "https://cloudmanic.github.io/skyclerk.com/"
languageCode = "en-us"
title = "Skyclerk"
publishDir = "docs"
disableHugoGeneratorInject = true
disableKinds = ["taxonomyTerm"]
summaryLength = 20

[taxonomies]
  category = "categories"
  supportCategory = "supportCategories"

[permalinks]
	categories = "/blog/:slug/"

[outputFormats.Algolia]
  baseName = "algolia"
  isPlainText = true
  mediaType = "application/json"
  notAlternative = true

[params.algolia]
  vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
  params = ["categories", "supportCategories"]


[outputs]
  home = ["HTML", "RSS", "Algolia"]
