---

# Set directory perms for nginx proxy directories
- name: Set directory perms for docker site nginx proxy directories
  file: path={{ docker_nginx_proxy_dir }} owner=deploy group=deploy mode=0770 state=directory
  when: docker_nginx_proxy
  
# Install nginx proxy docker-compose
- name: Install nginx proxy docker-compose
  template: src=docker-compose.yml dest={{ docker_nginx_proxy_dir }}/docker-compose.yml owner=deploy group=deploy mode=0640
  when: docker_nginx_proxy    

# Install nginx proxy env
- name: Install nginx proxy env
  template: src=env dest={{ docker_nginx_proxy_dir }}/.env owner=deploy group=deploy mode=0640 
  when: docker_nginx_proxy   
  
# Set directory perms for docker nginx proxy directories - vhost_config
- name: Set directory perms for docker site nginx proxy directories - vhost_config
  file: path={{ docker_nginx_proxy_dir }}/vhost_config owner=deploy group=deploy mode=0770 state=directory
  when: docker_nginx_proxy   

# Install nginx proxy vhost_config/default 
- name: Install core services vhost_config/default
  template: src=vhost_config_default dest={{ docker_nginx_proxy_dir }}/vhost_config/default owner=deploy group=deploy mode=0640
  when: docker_nginx_proxy

# Install docker network.
- name: Start docker shared network.
  command: docker network create shared
  ignore_errors: yes

# Start shared services
- name: Start nginx proxy
  command: docker-compose -f {{ docker_nginx_proxy_dir }}/docker-compose.yml up -d
  when: docker_nginx_proxy  