---

# Do a git repo checkout - Craft App
- name: Checkout git repo
  git: "repo={{ repo_url }} dest={{ site_path }}/app version={{ git_branch }} accept_hostkey=yes force=yes"

# Create docker directory
- name: Create docker directory
  file: path={{ site_path }}/docker owner={{ app_user }} group={{ app_user }} mode=0755 state=directory

# Create docker build directory
- name: Create docker build directory
  file: path={{ site_path }}/docker/build owner={{ app_user }} group={{ app_user }} mode=0755 state=directory

# Install docker-compose file
- name: set up remote docker-compose file
  template: src=docker-compose.yml dest="{{ site_path }}/docker/docker-compose.yml" mode=0644 owner={{ app_user }} group={{ app_user }}

# Install Dockerfile
- name: Install Dockerfile
  template: src=build/Dockerfile dest={{ site_path }}/docker/build/Dockerfile owner={{ app_user }} group={{ app_user }} mode=0644

# Install nginx.conf
- name: Install nginx.conf
  template: src=build/nginx.conf dest={{ site_path }}/docker/build/nginx.conf owner={{ app_user }} group={{ app_user }} mode=0644

# Install nginx_default.conf
- name: Install nginx_default.conf
  template: src=build/nginx_default.conf dest={{ site_path }}/docker/build/nginx_default.conf owner={{ app_user }} group={{ app_user }} mode=0644

# Install php.ini
- name: Install php.ini
  template: src=build/php.ini dest={{ site_path }}/docker/build/php.ini owner={{ app_user }} group={{ app_user }} mode=0644

# Install ENV File
- name: Install Docker ENV File
  template: src=docker-env dest={{ site_path }}/docker/.env owner={{ app_user }} group={{ app_user }} mode=0644

# Install ENV File
- name: Install ENV File
  template: src=env dest={{ site_path }}/app/.env owner={{ app_user }} group={{ app_user }} mode=0644
