---

# Setup host base directory
- name: Setup {{ backup_hostname }} base directory
  file: path={{ backup_site_dir }} owner={{ backup_user }} group={{ backup_group }} mode=0755 state=directory
  delegate_to: "{{ backup_host }}"

# Install docker-compose for host
- name: Install docker-compose for {{ backup_hostname }}
  template: src=docker-compose.yml dest={{ backup_site_dir }}/docker-compose.yml owner={{ backup_user }} group={{ backup_group }} mode=0644
  delegate_to: "{{ backup_host }}"

# Install ENV File for host
- name: Install ENV File for {{ backup_hostname }}
  template: src=env dest={{ backup_site_dir }}/.env owner={{ backup_user }} group={{ backup_group }} mode=0644
  delegate_to: "{{ backup_host }}"

# Pull docker
- name: Downloading lastest image for {{ backup_hostname }}
  command: docker-compose pull
  delegate_to: "{{ backup_host }}"
  args:
    chdir: "{{ backup_site_dir }}"

# Stop docker
- name: Stopping docker container for {{ backup_hostname }}
  command: docker-compose down --remove-orphans
  delegate_to: "{{ backup_host }}"  
  args:
    chdir: "{{ backup_site_dir }}"

# Start docker
- name: Starting docker for {{ backup_hostname }}
  command: docker-compose up -d
  delegate_to: "{{ backup_host }}"
  args:
    chdir: "{{ backup_site_dir }}"  