---

- name: Deploy backups for skyclerk.com to production

  hosts: servers

  become: yes

  become_user: root

  roles:
    - cloudmanic-backup

  vars_files:
    - "vars/encrypt.yml"
    - "vars/all.yml"
