---

- name: Deploys the server config for skyclerk.com to production

  hosts: servers

  become: yes

  become_user: root

  roles:
    - bootstrap
    - users
    - docker-sites
    - docker-mysql
    - docker-nginx-proxy

  vars_files:
    - "vars/encrypt.yml"
    - "vars/all.yml"
