# {{ ansible_managed }}

version: '2.1'

services:

  # App
  web:

    hostname: ${COMPOSE_PROJECT_NAME}

    container_name: ${COMPOSE_PROJECT_NAME}

    build:
      context: ./build
      dockerfile: Dockerfile
      args:
        P_UID: ${P_UID}
        P_GID: ${P_GID}

    image: ${COMPOSE_PROJECT_NAME}/nginx-php70

    restart: always

    environment:   
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}

    volumes:
      - ../app:/www:ro
      - ../app/storage:/www/storage:rw
      - ../app/web/cpresources:/www/web/cpresources:rw

    networks:
      - shared

networks:
  shared:
    external:
      name: shared
